### PR TITLE
Configure CI Github Actions workflow

### PR DESCRIPTION
**Pull request by drborges**
We'll be moving away from Travis in favor of Github Actions.

### CODE REVIEW

**Comment by drborges** [comment]
@benlangfeld I assume we'd want to account for bundler v1 and v2 like in cobra commander?

**Comment by drborges** [comment]
@delucas I removed ruby 2.7 and 3 from the CI workflow since you are working on the fix to support newer ruby versions. I figured you can add those versions to the workflow in your PR. Thoughts?

**Comment by benlangfeld** [comment]
> @benlangfeld I assume we'd want to account for bundler v1 and v2 like in cobra commander?

I don't think so. I think you can assume Bundler 2.

**Comment by drborges** [comment]
@benlangfeld regarding the release workflow, do you want that in this PR? If so, should we be using specific Github/Rubygems API keys?

**Comment by benlangfeld** [comment]
> @benlangfeld regarding the release workflow, do you want that in this PR? If so, should we be using specific Github/Rubygems API keys?

It might be nice, yeah. @xjunior set it up for cobra_commander.

**Comment by drborges** [comment]
@benlangfeld Are you ok with me implementing the release workflow in a follow-up PR so this one unblocks @delucas?

**Comment by drborges** [comment]
We'll be implementing the release workflow in a new PR so that Heroes for Hire can continue making progress on their work.

**Pull request merged**
